todoapp/apps/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

# app_name = 'accounts'
urlpatterns = [
    # path('login/', views.LoginView.as_view(), name='login'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path("edit", views.edit, name="edit"),
    path('password-change/', auth_views.PasswordChangeView.as_view(),name='password_change'),
    path('password-change-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    
    path('pwd-reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('pwd-reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('pwd-reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(),name='password_reset_confirm'),
    path('pwd-reset/complete/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

todoapp/apps/tasks/urls.py
from django.urls import path

from django.contrib.auth.decorators import login_required

from . import views

app_name = 'tasks'

urlpatterns = [
    path('', views.index, name='index'),
    # path('list/', views.task_list, name='list'),
    # path('list/', login_required(views.TaskListView.as_view()), name='list'),
    path('list/', views.TaskListView.as_view(), name='list'),

    # path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
    path('delete/<int:task_id>/', views.DeleteTaskView.as_view(), name='delete_task'),

    # path('complete/<int:task_id>/', views.complete_task, name='complete_task'),
    path('complete/<int:task_id>/', views.CompleteTaskView.as_view(), name='complete_task'),

    # path('create/', views.create_task, name='create_task'),
    path('create/', views.CreateTaskView.as_view(), name='create_task'),

    path("details/<int:pk>/", views.TaskDetailsView.as_view(), name="details"),

    path("edit/<int:pk>/", views.TaskEditView.as_view(), name="edit"),


    path('export/', views.TaskExportView.as_view(), name='export'),


    # path('add-task/', views.add_task, name='add_task'),
    path('publisher/', views.PublisherView.as_view(), name='publisher'),
    path('publisher/<int:id>/', views.PublisherView.as_view(), name='publisher'),
]

todoapp/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls', namespace='tasks')),
    path('tasks/', include('tasks.urls', namespace='tasks')),
    path('accounts/', include('accounts.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

todoapp/apps/accounts/models.py
from django.db import models

from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    birthdate = models.DateField(blank=True, null=True)
    # avatar = models.ImageField(upload_to='user_avatars/%Y/%m/%d', blank=True, default='user_avatars/avatar.jpeg')

    def __str__(self):
        return f"Профиль пользователя {self.user.username}"

todoapp/apps/tasks/models.py
from django.db import models
from django.urls import reverse

from django.contrib.auth.models import User

class TodoItem(models.Model):
    PRIORITY_HIGH = 1
    PRIORITY_MEDIUM = 2
    PRIORITY_LOW = 3

    PRIORITY_CHOICES = [
        (PRIORITY_HIGH, "Высокий приоритет"),
        (PRIORITY_MEDIUM, "Средний приоритет"),
        (PRIORITY_LOW, "Низкий приоритет"),
    ]
    # verbose_neme = <title>
    # help_text = <br><span>...</span>
    description = models.CharField(max_length=64)
    is_completed = models.BooleanField("выполнено", default=False)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    owner = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='tasks'
    )
    priority = models.IntegerField(
        "Приоритет", choices=PRIORITY_CHOICES, default=PRIORITY_MEDIUM
    )

    def __str__(self):
        return self.description.lower()

    def get_absolute_url(self):
        return reverse("tasks:details", args=[self.pk])

    class Meta:
        ordering = ('-created',)


class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

todoapp/apps/accounts/forms.py
from django import forms

from django.contrib.auth.models import User

from accounts.models import Profile

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'login'}))
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.ModelForm):
    password = forms.CharField(label='Пароль', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Повторите пароль', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'email')
    
    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('пароли не совпадают')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email')


class ProfileEditForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ("birthdate",)

todoapp/apps/tasks/forms.py
from django import forms
# from django.forms.widgets import SelectDateWidget

from tasks.models import TodoItem

# class AddTaskForm(forms.Form):
#     description = forms.CharField(max_length=64, label='', initial='')


# BIRTH_YEAR_CHOICES = ('1980', '1981', '1982')
# FAVORITE_COLORS_CHOICES = (('blue', 'Blue'),
#                             ('green', 'Green'),
#                             ('black', 'Black'))

# class SimpleForm(forms.Form):
#     birth_year = forms.DateField(widget=SelectDateWidget(years=BIRTH_YEAR_CHOICES))
#     favorite_colors = forms.MultipleChoiceField(required=False,
#         widget=forms.CheckboxSelectMultiple, choices=FAVORITE_COLORS_CHOICES)


# class CommentForm(forms.Form):
#     name = forms.CharField(widget=forms.TextInput(attrs={'class': 'special'}))
#     url = forms.URLField()
#     comment = forms.CharField(widget=forms.TextInput(attrs={'size': '40'}))


class AddTaskForm(forms.ModelForm):
    class Meta:
        model = TodoItem
        fields = ('description', 'priority',)
        labels = {'description': '', 'priority': '',}


class TodoItemExportForm(forms.Form):
    prio_high = forms.BooleanField(label='высокой важности', initial=True, required=False)
    prio_med = forms.BooleanField(label='средней важности', initial=True, required=False)
    prio_low = forms.BooleanField(label='низкой важности', initial=False, required=False)

todoapp/apps/accounts/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
from django.contrib.auth import authenticate, login

# from django.urls import reverse

from accounts.forms import LoginForm, RegistrationForm, UserEditForm, ProfileEditForm
from accounts.models import Profile

class LoginView(View):
    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(
                request,
                username=cd['username'],
                password=cd['password'],
            )
            if user is None:
                return HttpResponse('Неправильный логин и/или пароль')
            
            if not user.is_active:
                return HttpResponse('Ваш аккаунт заблокирован')
            
            login(request, user)
            return HttpResponse('Добро пожаловать! Успешный вход')
        return render(request, 'accounts/login.html', {'form': form})
    
    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(form.cleaned_data['password'])
            new_user.save()

            Profile.objects.create(user=new_user)

            return render(request, 'accounts/registration_complete.html', {
                'new_user': new_user,
            })
    else:
        form = RegistrationForm()
    
    return render(request, 'accounts/register.html', {
        'user_form': form,
    })


def edit(request):
    if request.method == 'POST':
        user_form = UserEditForm(
            instance=request.user, 
            data=request.POST
        )

        profile_form = ProfileEditForm(
            instance=request.user.profile, 
            data=request.POST,
            files=request.FILES    
        )

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
    else:
        user_form = UserEditForm(instance=request.user)
        profile_form = ProfileEditForm(instance=request.user.profile)
    
    return render(request, 'accounts/edit.html', {
        'user_form': user_form,
        'profile_form': profile_form,
    })

todoapp/apps/tasks/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from django.urls import reverse

from django.views.generic import ListView, View, DetailView

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib import messages

from django.db.models import Q

# for smtp
from django.core.mail import send_mail
from django.conf import settings

from tasks.models import TodoItem, Publisher
from tasks.forms import AddTaskForm, TodoItemExportForm



def get_task_by_id(task_id):
    try:
        task = TodoItem.objects.get(id = task_id)
    except:
        return False
    return task


@login_required
def index(request):
    return HttpResponseRedirect(reverse('tasks:list'))


'''
def task_list(request):
    tasks = TodoItem.objects.all()
    return render(request, 'tasks/list.html', {
        'tasks': tasks
    })
'''

# страница доступна только для авторизованных пользователей
# class TaskListView(LoginRequiredMixin, ListView):
class TaskListView(LoginRequiredMixin, ListView):
    model = TodoItem
    context_object_name = 'tasks'
    template_name = 'tasks/list.html'

    def get_queryset(self):
        u = self.request.user
        if u.is_anonymous:
            return []
        return u.tasks.all()


'''
def delete_task(request, task_id):
    task = get_task_by_id(task_id)
    if not task:
        return Http404('Task not found')

    task.delete()
    return HttpResponseRedirect(reverse('tasks:list'))
'''

class DeleteTaskView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if 'task_id' in kwargs:
            task = get_task_by_id(kwargs['task_id'])
        else:
            return Http404('Wrong reqest')

        if not task:
            return Http404('Task not found')
        task.delete()
        messages.success(request, "Задача удалена")
            # messages.error(request, "Задача удалена")
            # messages.info(request, "Задача удалена")
            # messages.warning(request, "Задача удалена")

        return HttpResponseRedirect(reverse('tasks:list'))


'''
def complete_task(request, task_id):
    task = get_task_by_id(task_id)
    if not task:
        return HttpResponse('ERROR')
    
    task.is_completed = True
    task.save()
    return HttpResponse('OK')
'''


class CompleteTaskView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        if 'task_id' in kwargs:
            task = get_task_by_id(kwargs['task_id'])
        else:
            return Http404('Wrong reqest')
        
        task = get_task_by_id(kwargs['task_id'])
        if not task:
            return Http404('Task not found')
    
        task.is_completed = True
        task.save()
        return HttpResponse('OK')




'''
def create_task(request):
    # Вариант, для не модельной формы
    # if request.method == 'POST':
    #     form = AddTaskForm(request.POST)
    #     if form.is_valid():
    #         cd = form.cleaned_data
    #         desc = cd['description']
    #         t = TodoItem(description=desc)
    #         t.save()
    if request.method == 'POST':
        form = AddTaskForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('tasks:list'))
    else:
        form = AddTaskForm()
    return render(request, 'tasks/create.html', {
        'form': form,
    })
'''


class CreateTaskView(LoginRequiredMixin, View):
    def my_render(self, request, form):
        return render(request, "tasks/create.html", {"form": form})

    def post(self, request, *args, **kwargs):
        form = AddTaskForm(request.POST)
        if form.is_valid():
            # form.save()
            # подмешаем юзера в форму
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return HttpResponseRedirect(reverse('tasks:list'))


        return self.my_render(request, form)

    def get(self, request, *args, **kwargs):
        form = AddTaskForm()
        return self.my_render(request, form)


# def add_task(request):
#     if request.method == 'POST':
#         desc = request.POST['description']
#         if len(desc):
#             t = TodoItem(description=desc)
#             t.save()
#     return HttpResponseRedirect(reverse('tasks:create_task'))


class TaskDetailsView(LoginRequiredMixin, DetailView):
    model = TodoItem
    template_name = 'tasks/details.html'
    # объект будет доступен по имени object


class TaskEditView(LoginRequiredMixin, View):
    def post(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = AddTaskForm(request.POST, instance=t)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.owner = request.user
            new_task.save()
            return HttpResponseRedirect(reverse("tasks:list"))

        return render(request, "tasks/edit.html", {"form": form, "task": t})

    def get(self, request, pk, *args, **kwargs):
        t = TodoItem.objects.get(id=pk)
        form = AddTaskForm(instance=t)
        return render(request, "tasks/edit.html", {"form": form, "task": t})



class PublisherView(ListView):
    model = Publisher
    context_object_name = 'publishers'
    template_name = 'tasks/publisher.html'

    # достаём подмножество
    def get_queryset(self):
        if 'id' in self.kwargs:
            self.publisher = get_object_or_404(Publisher, id=self.kwargs['id'])
            return [self.publisher]
        else:
            return Publisher.objects.all()

    # расширение контекста
    def get_context_data(self, **kwargs):
        context = super(PublisherView, self).get_context_data(**kwargs)
        context['tasks'] = TodoItem.objects.all()
        return context


class TaskExportView(LoginRequiredMixin, View):
    def generate_body(self, user, priorities):
        q = Q()
        if priorities['prio_high']:
            q = q | Q(priority=TodoItem.PRIORITY_HIGH)
        if priorities["prio_med"]:
            q = q | Q(priority=TodoItem.PRIORITY_MEDIUM)
        if priorities["prio_low"]:
            q = q | Q(priority=TodoItem.PRIORITY_LOW)
        tasks = TodoItem.objects.filter(owner=user).filter(q).all()

        body = 'Ваши задачи и приоритеты:\n'
        for t in list(tasks):
            if t.is_completed:
                body += f'[x] {t.description} ({ t.get_priority_display() })\n'
            else:
                body += f"[ ] {t.description} ({t.get_priority_display()})\n"
        return body
    
    def post(self, request, *args, **kwargs):
        form = TodoItemExportForm(request.POST)
        if form.is_valid():
            email = request.user.email
            body = self.generate_body(request.user, form.cleaned_data)
            send_mail("Задачи", body, settings.EMAIL_HOST_USER, [email])
            messages.success(
                request, "Задачи были отправлены на почту %s" % email)
        else:
            messages.error(request, "Что-то пошло не так, попробуйте ещё раз")
        return HttpResponseRedirect(reverse("tasks:list"))

    def get(self, request, *args, **kwargs):
        form = TodoItemExportForm()
        return render(request, "tasks/export.html", {"form": form})

todoapp/templates/tasks/create.html
{% extends "base.html" %}
{% load static %}

{% block title %}create task{% endblock title %}

{% block extend_static %}
<link rel="stylesheet" href="{% static 'tasks/css/create.css' %}">
{% endblock extend_static %}


{% block content %}
  <div class="container center">
    <h1>Создать задачу</h1>
    <form action="{% url 'tasks:create_task' %}" method="POST">
        {% csrf_token %}
        <div class="add_form">
          {{ form }}
          <button class="add" type="submit">+</button>
        </div>
    </form>
  </div>
{% endblock content %}


{% block javascript %}
<script src="{% static 'tasks/js/create_task.js' %}"></script>
{% endblock javascript %}

todoapp/templates/tasks/details.html
{% extends "base.html" %}
{% load static %}

{% block extend_static %}
{% endblock extend_static %}

{% block title %}Задача{{ object.id }}{% endblock %}

{% block content %}
    <div class="container">
        <h1>Задача</h1>
        <p><b>Описание</b>: {{ object.description }}</p>
        <ul>
            <li>Задача
                {{ object.is_completed|yesno:"выполнена,ещё не выполнена" }}
            </li>
            <li>Создана: {{ object.created|date:"Y b d H:i" }}</li>
            <li>Последнее изменение: {{ object.updated|date:"Y b d H:i" }}</li>
            <li><i class="far fa-edit"></i>&nbsp;<a href="{% url "tasks:edit" pk=object.pk %}">Редактировать</a></li>

        </ul>
        <a href="{% url "tasks:list" %}">Назад к списку</a>
    </div>
{% endblock %}

todoapp/templates/tasks/edit.html
{% extends "base.html" %}

{% block title %}Изменить задачу{% endblock %}

{% block content %}
  <h1>Поменять задачу</h1>  
  <form action="{% url "tasks:edit" task.pk %}" method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Сохранить</button></p>
  </form>
{% endblock %}

todoapp/templates/tasks/export.html
{% extends "base.html" %}

{% block title %}Экспорт{% endblock %}

{% block content %}
  <h1>Экспорт задач</h1>
  <p>На вашу почту придёт емейл с задачами. Уточните список.</p>
  <form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <p><button class="add" type="submit">Жмяк</button></p>
  </form>
{% endblock %}

todoapp/templates/tasks/list.html
{% extends "base.html" %}
{% load static %}

{% block extend_static %}
  <link rel="stylesheet" href="{% static 'tasks/css/styles.css' %}">
{% endblock extend_static %}

{% block title %}
  task list
{% endblock title %}

{% block content %}
  <h1>Текущие задачи</h1>
  <p><i class="fa fa-download"></i>&nbsp;<a href="{% url 'tasks:export' %}">экспорт</a></h1>
  <ul id="todo-list">
  {% for task in tasks %}
    {% if task.is_completed %}
    <li class="completed list_item">
      <input class='checkbox' data-uid={{ task.id }} type='checkbox' disabled='disabled' checked='checked'/>
    {% else %}
    <li class="list_item">
      <input class='checkbox in_progress' data-uid={{ task.id }} type='checkbox' />
    {% endif %}

    {% if task.priority == task.PRIORITY_HIGH %}
      <span class="badge badge-pill badge-danger">&nbsp;</span>
    {% elif task.priority == task.PRIORITY_MEDIUM %}
      <span class="badge badge-pill badge-secondary">&nbsp;</span>
    {% elif task.priority == task.PRIORITY_LOW %}
      <span class="badge badge-pill badge-success">&nbsp;</span>
    {% endif %}

      <a href={% url "tasks:details" task.id %}>{{ task }}</a>
      <!-- <a class="remove" href="/api/delete/{{ task.id }}">X</a> -->
      <a class="remove" href="{% url 'tasks:delete_task' task.id %}">X</a>
      <hr/>
    </li>
  {% endfor %}
  </ul>
</div>
{% endblock content %}

{% block javascript %}
  <script src="{% static 'tasks/js/script.js' %}"></script>
{% endblock javascript %}

todoapp/templates/tasks/publisher.html
{% extends "base.html" %}
{% load static %}

{% block title %}publisher{% endblock title %}

{% block extend_static %}

{% endblock extend_static %}


{% block content %}
<h2>Publishers</h2>
<ul>
    {% for publisher in publishers %}
        <li>{{ publisher.name }}</li>
    {% endfor %}
</ul>

<h2>Tasks</h2>
<ul>
    {% for task in tasks %}
        <li>{{ task.description }}</li>
    {% endfor %}
</ul>
{% endblock content %}


{% block javascript %}

{% endblock javascript %}